name: "Auto-advance Deal to Negotiation"
description: "Move deal to negotiation when quote sent"
trigger:
  type: DEAL_STAGE_CHANGED
  event: "deal.stage_changed"

conditions:
  - field: "deal.stage"
    operator: "equals"
    value: "PROPOSAL"
  - field: "deal.probability"
    operator: "greater_than"
    value: 60

actions:
  - type: "update_field"
    params:
      entity: "deal"
      field: "stage"
      value: "NEGOTIATION"
  - type: "create_task"
    params:
      title: "Follow up on proposal: {{deal.title}}"
      assigned_to_id: "{{deal.owner_id}}"
      due_date: "+3days"
